
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 07 01:49:44 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 20;
  public static final int PARFERMANTE = 19;
  public static final int CSTENTIERE = 21;
  public static final int PLUS = 27;
  public static final int OPERLOGIQUEA = 24;
  public static final int LIRE = 8;
  public static final int ECRIRE = 6;
  public static final int OPERET = 25;
  public static final int TANTQUE = 14;
  public static final int ALORS = 11;
  public static final int OPERB = 23;
  public static final int OPERA = 22;
  public static final int REPETER = 15;
  public static final int NON = 17;
  public static final int MOINS = 28;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 16;
  public static final int SINON = 12;
  public static final int EGALE = 9;
  public static final int ENTIER = 7;
  public static final int EOF = 0;
  public static final int OPEROU = 26;
  public static final int PAROUVRANTE = 18;
  public static final int SI = 10;
  public static final int error = 1;
  public static final int OPERNEGALE = 30;
  public static final int DEBUT = 3;
  public static final int OPEREGALE = 29;
  public static final int FINSI = 13;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

