
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 08 15:49:04 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 19;
  public static final int PARFERMANTE = 18;
  public static final int CSTENTIERE = 20;
  public static final int PLUS = 25;
  public static final int OPERLOGIQUEA = 22;
  public static final int LIRE = 8;
  public static final int ECRIRE = 6;
  public static final int OPERET = 23;
  public static final int TANTQUE = 14;
  public static final int ALORS = 11;
  public static final int OPERB = 21;
  public static final int REPETER = 15;
  public static final int NON = 29;
  public static final int MOINS = 26;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 16;
  public static final int SINON = 12;
  public static final int EGALE = 9;
  public static final int ENTIER = 7;
  public static final int EOF = 0;
  public static final int OPEROU = 24;
  public static final int PAROUVRANTE = 17;
  public static final int SI = 10;
  public static final int error = 1;
  public static final int OPERNEGALE = 28;
  public static final int DEBUT = 3;
  public static final int OPEREGALE = 27;
  public static final int FINSI = 13;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

